apiVersion: v1
kind: Service
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30085
      protocol: TCP
      name: http
  selector:
    app: drupal
